# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_DSN=postgres://${DB_USER}:${POSTGRES_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - TMDB_API_KEY=${TMDB_API_KEY}
      - TMDB_BASE_URL=${TMDB_BASE_URL}
      - TMDB_BACKLOAD_HIGH_WATERMARK_DATE=${TMDB_BACKLOAD_HIGH_WATERMARK_DATE}
  db:
    build: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: