// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: movieswatchedbyuser.sql

package db

import (
	"context"
)

const getMoviesWatchedByUser = `-- name: GetMoviesWatchedByUser :many
select user_id, movie_id, experience_stars
from movies_watched_by_user
where user_id = $1
`

func (q *Queries) GetMoviesWatchedByUser(ctx context.Context, userID int) ([]MoviesWatchedByUser, error) {
	rows, err := q.db.Query(ctx, getMoviesWatchedByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MoviesWatchedByUser
	for rows.Next() {
		var i MoviesWatchedByUser
		if err := rows.Scan(&i.UserID, &i.MovieID, &i.ExperienceStars); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMovieWatchedByUser = `-- name: RemoveMovieWatchedByUser :exec
delete
from movies_watched_by_user
where user_id = $1
  and movie_id = $2
`

func (q *Queries) RemoveMovieWatchedByUser(ctx context.Context, userID int, movieID int) error {
	_, err := q.db.Exec(ctx, removeMovieWatchedByUser, userID, movieID)
	return err
}

const upsertMovieWatchedByUser = `-- name: UpsertMovieWatchedByUser :exec
INSERT INTO movies_watched_by_user (user_id, movie_id, experience_stars)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, movie_id)
    DO UPDATE SET experience_stars = EXCLUDED.experience_stars
`

func (q *Queries) UpsertMovieWatchedByUser(ctx context.Context, userID int, movieID int, experienceStars int) error {
	_, err := q.db.Exec(ctx, upsertMovieWatchedByUser, userID, movieID, experienceStars)
	return err
}
