// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Movie struct {
	ID          int
	Title       string
	ReleaseDate string
	Overview    string
	PosterUrl   string
	TrailerUrl  string
	Rating      float64
	RawData     string
	CreatedAt   pgtype.Timestamp
}

type MoviesWatchedByUser struct {
	UserID          int
	MovieID         int
	ExperienceStars int
}

type User struct {
	ID        int
	Email     string
	AuthToken string
	Expiry    pgtype.Timestamp
}
