// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Movie struct {
	ID          string
	Title       string
	Description string
	PosterUrl   string
	TrailerUrl  string
	Rating      float64
}

type MoviesWatchedByUser struct {
	UserID          int32
	MovieID         string
	ExperienceStars int32
}

type User struct {
	ID    int32
	Email string
}
